name: score-plotting-default-env
channels:
  - conda-forge
dependencies:
  - python >= 3.9
  - numpy
  - pyyaml
  - pytest
  - xarray
  - dask
  - pandas
  - netcdf4
  - scipy
  - sqlalchemy=1.4.49
  - matplotlib
  - python-dotenv
  - psycopg2
  - geoalchemy2
  - sqlalchemy-utils
  - colorcet
  - jupyterlab
