def get_satellite_names():
    sats = {
    "NOAA-5": {"sat_id": 705, "short_name": "n05"},
    "NOAA-6": {"sat_id": 706, "short_name": "n06"},
    "NOAA-7": {"sat_id": 707, "short_name": "n07"},
    "NOAA-8": {"sat_id": 708, "short_name": "n08"},
    "NOAA-9": {"sat_id": 709, "short_name": "n09"},
    "NOAA-10": {"sat_id": 710, "short_name": "n10"},
    "NOAA-11": {"sat_id": 711, "short_name": "n11"},
    "NOAA-12": {"sat_id": 712, "short_name": "n12"},
    "NOAA-13": {"sat_id": 713, "short_name": "n13"},
    "NOAA-14": {"sat_id": 714, "short_name": "n14"},
    "NOAA-15": {"sat_id": 715, "short_name": "n15"},
    "NOAA-16": {"sat_id": 716, "short_name": "n16"},
    "NOAA-17": {"sat_id": 717, "short_name": "n17"},
    "NOAA-18": {"sat_id": 718, "short_name": "n18"},
    "NOAA-19": {"sat_id": 719, "short_name": "n19"},
    "NOAA-20": {"sat_id": 720, "short_name": "n20"},
    "NOAA-21": {"sat_id": 721, "short_name": "n21"},
    "MetOp-A": {"sat_id": 3, "short_name": "metop-a"},
    "MetOp-B": {"sat_id": 4, "short_name": "metop-b"},
    "MetOp-C": {"sat_id": 5, "short_name": "metop-c"},
    "Aqua": {"sat_id": 784, "short_name": "aqua"},
    "Suomi NPP": {"sat_id": 224, "short_name": "npp"},
    "GOES-7": {"sat_id": 251, "short_name": "g07"},
    "GOES-8": {"sat_id": 252, "short_name": "g08"},
    "GOES-9": {"sat_id": 253, "short_name": "g09"},
    "GOES-10": {"sat_id": 254, "short_name": "g10"},
    "GOES-11": {"sat_id": 255, "short_name": "g11"},
    "GOES-12": {"sat_id": 256, "short_name": "g12"},
    "GOES-13": {"sat_id": 257, "short_name": "g13"},
    "GOES-14": {"sat_id": 258, "short_name": "g14"},
    "GOES-15": {"sat_id": 259, "short_name": "g15"},
    "GOES-16": {"sat_id": 270, "short_name": "g16"},
    "GOES-17": {"sat_id": 271, "short_name": "g17"},
    "GOES-18": {"sat_id": 272, "short_name": "g18"},
    #"MTSAT-2": {"sat_id": 172, "short_name": "MTSAT-2"},
    #"MTSAT-1R": {"sat_id": 171, "short_name": "MTSAT-1R"},
    "Meteosat-2": {"sat_id": 59, "short_name": "m02"},
    "Meteosat-3": {"sat_id": 51, "short_name": "m03"},
    "Meteosat-4": {"sat_id": 52, "short_name": "m04"},
    "Meteosat-5": {"sat_id": 53, "short_name": "m05"},
    "Meteosat-6": {"sat_id": 54, "short_name": "m06"},
    "Meteosat-7": {"sat_id": 55, "short_name": "m07"},
    "Meteosat-8": {"sat_id": 56, "short_name": "m08"},
    "Meteosat-9": {"sat_id": 57, "short_name": "m09"},
    "Meteosat-10": {"sat_id": 67, "short_name": "m10"},
    "Meteosat-11": {"sat_id": 70, "short_name": "m11"},
    "DMSP-F08": {"sat_id": 241, "short_name": "f08"},
    "DMSP-F09": {"sat_id": 242, "short_name": "f09"},
    "DMSP-F10": {"sat_id": 243, "short_name": "f10"},
    "DMSP-F11": {"sat_id": 244, "short_name": "f11"},
    "DMSP-F12": {"sat_id": 245, "short_name": "f12"},
    "DMSP-F13": {"sat_id": 246, "short_name": "f13"},
    "DMSP-F14": {"sat_id": 247, "short_name": "f14"},
    "DMSP-F15": {"sat_id": 248, "short_name": "f15"},
    "DMSP-F16": {"sat_id": 249, "short_name": "f16"},
    "DMSP-F17": {"sat_id": 285, "short_name": "f17"},
    "DMSP-F18": {"sat_id": 286, "short_name": "f18"},
    "DMSP-F19": {"sat_id": 39630, "short_name": "f19"},
    "DMSP-F20": {"sat_id": 41705, "short_name": "f20"},
    #"CHAMP": {"sat_id": 41, "short_name": "CHAMP"},
    #"COSMIC-1": {"sat_id": 740, "short_name": "COSMIC-1"},
    #"COSMIC-2": {"sat_id": 741, "short_name": "COSMIC-2"},
    #"COSMIC-3": {"sat_id": 742, "short_name": "COSMIC-3"},
    #"COSMIC-4": {"sat_id": 743, "short_name": "COSMIC-4"},
    #"COSMIC-5": {"sat_id": 744, "short_name": "COSMIC-5"},
    #"COSMIC-6": {"sat_id": 745, "short_name": "COSMIC-6"},
    #"COSMIC-2 E1": {"sat_id": 750, "short_name": "COSMIC-2 E1"},
    #"COSMIC-2 E2": {"sat_id": 751, "short_name": "COSMIC-2 E2"},
    #"COSMIC-2 E3": {"sat_id": 752, "short_name": "COSMIC-2 E3"},
    #"COSMIC-2 E4": {"sat_id": 753, "short_name": "COSMIC-2 E4"},
    #"COSMIC-2 E5": {"sat_id": 754, "short_name": "COSMIC-2 E5"},
    #"COSMIC-2 E6": {"sat_id": 755, "short_name": "COSMIC-2 E6"},
    #"GRACE A": {"sat_id": 722, "short_name": "GRACE A"},
    #"GRACE B": {"sat_id": 723, "short_name": "GRACE B"},
    #"GRACE C (GRACE-F": {"sat_id": 803, "short_name": "GRACE C"},
    #"GRACE D (GRACE-F": {"sat_id": 804, "short_name": "GRACE D"},
    #"SAC-C": {"sat_id": 820, "short_name": "SAC C"},
    #"TerraSAR-X": {"sat_id": 42, "short_name": "TerraSAR-X"},
    #"Terra": {"sat_id": 783, "short_name": "TERRA"},
    #"ERS 2": {"sat_id": 2, "short_name": "ERS 2"},
    #"GMS-3": {"sat_id": 150, "short_name": "GMS 3"},
    #"GMS-4": {"sat_id": 151, "short_name": "GMS 4"},
    #"GMS-5": {"sat_id": 152, "short_name": "GMS 5"},
    #"INSAT 3A": {"sat_id": 470, "short_name": "INSAT 3A"},
    #"INSAT 3D": {"sat_id": 471, "short_name": "INSAT 3D"},
    #"INSAT 3DR": {"sat_id": 472, "short_name": "INSAT 3DR"},
    "TIROS-N": {"sat_id": 254, "short_name": "tirosn"},
    "Megha-Tropiques": {"sat_id": 367, "short_name": "meghat"},
    #"TanDEM-X": {"sat_id": 551, "short_name": "TanDEM-X"},
    #"PAZ": {"sat_id": 431, "short_name": "PAZ"},
    #"KOMPSAT-5": {"sat_id": 536, "short_name": "KOMPSAT-5"},
    #"LANDSAT 5": {"sat_id": 207, "short_name": "LANDSAT 5"},
    "GPM Core Observatory": {"sat_id": 371, "short_name": "gpm"},
    "TRMM": {"sat_id": 241, "short_name": "trmm"},
    "Himawari-8": {"sat_id": 370, "short_name": "himawari8"},
    "Himawari-9": {"sat_id": 372, "short_name": "himawari9"},
    #"Spire Lemur 3U C": {"sat_id": 409, "short_name": "Spire L3UC"},
    #"Sentinel 6A": {"sat_id": 835, "short_name": "Sentinel 6A"},
    #"PlanetiQ GNOMES-": {"sat_id": 687, "short_name": "PlanetiQ GNOMES"},
    #"Aura": {"sat_id": 296, "short_name": "AURA"},
    #"NIMBUS 7": {"sat_id": 16, "short_name": "nim07"},
    "GCOM-W": {"sat_id":'xxx', "short_name": "gcom-w1"},
    }
    return sats
    
def get_longname(short_name):
    dict_of_dicts = get_satellite_names()
    for top_level_key, inner_dict in dict_of_dicts.items():
        if 'short_name' in inner_dict and inner_dict['short_name'] == short_name:
            return top_level_key
    return short_name  # return short_name if no match is found
